     # -ti -e DISPLAY=$DISPLAY \
     # -v $workspace:/home/userpp/workspace \
     # -v $(realpath $rootdir/omnetpy):/home/userpp/omnetpy \
     # -e OMNETPY_ROOT=/home/userpp/workspace/omnetpy/omnetpy \
     # --privileged \
     # -v /tmp/.X11-unix:/tmp/.X11-unix \
     # nadfity/omnetpy bash

version: "3.6"
services:
  omnetpyenv:
    image: nadfity/omnetpy:6.0pre10
    volumes:
      - ${workspace}:/home/userpp/workspace
      - ${omnetpydir}:/home/userpp/omnetpy
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=$DISPLAY
      - OMNETPY_ROOT=/home/userpp/workspace/omnetpy/omnetpy
    privileged: true
    network_mode: "host"
    entrypoint: /bin/bash
    command: "-c 'while [ 1 ]; do sleep 10; done'"
